[env:esp32p4_m5stack]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = esp32-p4-evboard
framework = arduino

upload_speed = 1500000
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

build_type = debug
build_unflags = -mlongcalls
lib_ldf_mode = deep

board_build.mcu = esp32p4
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_INCLUDE_SIMPLE
    
    ; ==============================================================
    ; FIX: Unterdrückt die nervigen LVGL-8 GCC-14 Warnungen im Log
    -Wno-deprecated-enum-enum-conversion
    ; ==============================================================
    
    -I src
    -I src/config
    -I src/gui/core
    -I src/gui/baby
    -I src/gui/cat
    -I src/gui/ha
    -I src/gui/ha/HaDialogs
    -I src/gui/ha/HaWidgets
    -I src/gui/fonts
    -I src/ha
    -I src/media
    -I src/system


lib_deps = 
    lvgl/lvgl@8.3.11
    knolleary/PubSubClient@^2.8
    m5stack/M5GFX@0.2.19
    tobozo/LGFX_PPA@^0.2.2
    m5stack/M5Unified@0.2.13
    https://github.com/earlephilhower/ESP8266Audio.git
    bblanchon/ArduinoJson@^7.0.4
    gilmaimon/ArduinoWebsockets@^0.5.4
    ; NEU: Der offizielle CDC-ACM Wrapper für ESP-Hosts (Perfekt für den Dongle)
    https://github.com/bertmelis/USBHostSerial.git
    